// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdcqzeBb3ADxZIRj6X9tvmz8PB-MZBN7c',
    appId: '1:488906826387:web:f5083c81d793cae232e366',
    messagingSenderId: '488906826387',
    projectId: 'pirataflix-ad002',
    authDomain: 'pirataflix-ad002.firebaseapp.com',
    storageBucket: 'pirataflix-ad002.appspot.com',
    measurementId: 'G-MZHH4PM7DD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6F3dVL0Opi2A3UFWu-k3y2tXKljQn5OE',
    appId: '1:488906826387:android:bc0c98129f4c9a5d32e366',
    messagingSenderId: '488906826387',
    projectId: 'pirataflix-ad002',
    storageBucket: 'pirataflix-ad002.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4Nyt87Sv73z1ICigKxTYK6RTT5YsnvUo',
    appId: '1:488906826387:ios:6042f27413d73f7232e366',
    messagingSenderId: '488906826387',
    projectId: 'pirataflix-ad002',
    storageBucket: 'pirataflix-ad002.appspot.com',
    iosClientId: '488906826387-v5bgvnft4hdqmfb1g14qvgi9um4do7gm.apps.googleusercontent.com',
    iosBundleId: 'com.example.pirataFlix',
  );
}
